package com.mohitchahal.helloworld;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.DividerItemDecoration;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.TableRow;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    private final List<Region> regions = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        regions.add(new Region("Zone", "Province", "Area", null));
        regions.add(new Region("Trans-Himalayan", "Upper Regions", "186,200", "<h1>The Trans-Himalayan Region</h1><br />It constitutes 5.6 per cent of the total geographical area, includes the high altitude, cold and arid mountain areas of Ladakh, Jammu & Kashmir, North Sikkim, Lahaul and Spiti areas of Himachal Pradesh.\n<b>Flaura:</b> Alpine steppe vegetation\n<b>Fauna:</b> Snow Leopard, Blacknecked Crane (migratory)"));

        regions.add(new Region("Himalayan", "North West Himalayas", "6900", "<h1>The Himalayan Region</h1><br>The Himalayas consist of the youngest and loftiest mountain chains in the world. The Himalayas have attained a unique personality owing to their high altitude, steep gradient and rich temperate flora.\n" +
                "\n" +
                "<br /> <br />The forests are very dense with extensive growth of grass and evergreen tall trees. Oak, chestnut, conifer, ash, pine, deodar are abundant in Himalayas. There is no vegetation above the snowline. Several interesting animals live in the Himalayan ranges. Chief species include wild sheep, mountain goats, ibex, shrew, and tapir. Panda and snow leopard are also found here.\n" +
                "\n"));
        regions.add(new Region("", "West Himalayas", "720,000", "<h1>The Himalayan Region</h1><br>The Himalayas consist of the youngest and loftiest mountain chains in the world. The Himalayas have attained a unique personality owing to their high altitude, steep gradient and rich temperate flora.\n" +
        "\n" +
                "<br /> <br />The forests are very dense with extensive growth of grass and evergreen tall trees. Oak, chestnut, conifer, ash, pine, deodar are abundant in Himalayas. There is no vegetation above the snowline. Several interesting animals live in the Himalayan ranges. Chief species include wild sheep, mountain goats, ibex, shrew, and tapir. Panda and snow leopard are also found here.\n" +
                "\n"));
        regions.add(new Region("", "Central Himalayas", "123,000", "<h1>The Himalayan Region</h1><br>The Himalayas consist of the youngest and loftiest mountain chains in the world. The Himalayas have attained a unique personality owing to their high altitude, steep gradient and rich temperate flora.\n" +
        "\n" +
                "<br /> <br />The forests are very dense with extensive growth of grass and evergreen tall trees. Oak, chestnut, conifer, ash, pine, deodar are abundant in Himalayas. There is no vegetation above the snowline. Several interesting animals live in the Himalayan ranges. Chief species include wild sheep, mountain goats, ibex, shrew, and tapir. Panda and snow leopard are also found here.\n" +
                "\n"));
        regions.add(new Region("", "East Himalayas", "83,000", "<h1>The Himalayan Region</h1><br>The Himalayas consist of the youngest and loftiest mountain chains in the world. The Himalayas have attained a unique personality owing to their high altitude, steep gradient and rich temperate flora.\n" +
        "\n" +
                "<br /> <br />The forests are very dense with extensive growth of grass and evergreen tall trees. Oak, chestnut, conifer, ash, pine, deodar are abundant in Himalayas. There is no vegetation above the snowline. Several interesting animals live in the Himalayan ranges. Chief species include wild sheep, mountain goats, ibex, shrew, and tapir. Panda and snow leopard are also found here.\n" +
                "\n"));

        regions.add(new Region("Desert", "Kutch", "45,000", "<h1>The Desert Region</h1><br />This region consists of parts of Rajasthan, Kutch, Delhi and parts of Gujarat. The climate is characterised by very hot and dry summer and cold winter. Rainfall is less than 70 cm.<br /><br /> The plants are mostly xerophytic. Babul, Kikar, wild palm grows in areas of moderate rainfall. Indian Bustard, a highly endangered bird is found here. Camels, wild asses, foxes, and snakes are found in hot and arid parts of the desert.\n" +
                "\n"));
        regions.add(new Region("", "Thar", "180,000", "<h1>The Desert Region</h1><br />This region consists of parts of Rajasthan, Kutch, Delhi and parts of Gujarat. The climate is characterised by very hot and dry summer and cold winter. Rainfall is less than 70 cm.<br /><br /> The plants are mostly xerophytic. Babul, Kikar, wild palm grows in areas of moderate rainfall. Indian Bustard, a highly endangered bird is found here. Camels, wild asses, foxes, and snakes are found in hot and arid parts of the desert.\n" +
        "\n"));
        regions.add(new Region("", "Ladakh", "NA", "<h1>The Desert Region</h1><br />This region consists of parts of Rajasthan, Kutch, Delhi and parts of Gujarat. The climate is characterised by very hot and dry summer and cold winter. Rainfall is less than 70 cm.<br /><br /> The plants are mostly xerophytic. Babul, Kikar, wild palm grows in areas of moderate rainfall. Indian Bustard, a highly endangered bird is found here. Camels, wild asses, foxes, and snakes are found in hot and arid parts of the desert.\n" +
        "\n"));

        regions.add(new Region("Semi-Arid", "Central India", "107,600", "<h1>The Semi-Arid Region</h1><br />Adjoining the desert are the semi-arid areas, a transitional zone between the desert and the denser forests of the Western Ghats. The natural vegetation is thorn forest. This region is characterized by discontinuous vegetation cover with open areas of bare soil and soil-water deficit throughout the year.\n<br /><br />" +
                "\n" +
                "Thorny shrubs, grasses and some bamboos are present in some regions. A few species of xerophytic herbs and some ephemeral herbs are found in this semi-arid tract. Birds, jackals, leopards, eagles, snakes, fox, buffaloes are found in this region.\n" +
                "\n"));
        regions.add(new Region("", "Gujrat-Rajwara", "400,400", "<h1>The Semi-Arid Region</h1><br />Adjoining the desert are the semi-arid areas, a transitional zone between the desert and the denser forests of the Western Ghats. The natural vegetation is thorn forest. This region is characterized by discontinuous vegetation cover with open areas of bare soil and soil-water deficit throughout the year.\n<br /><br />" +
        "\n" +
                "Thorny shrubs, grasses and some bamboos are present in some regions. A few species of xerophytic herbs and some ephemeral herbs are found in this semi-arid tract. Birds, jackals, leopards, eagles, snakes, fox, buffaloes are found in this region.\n" +
                "\n"));

        regions.add(new Region("Western Ghats", "Malabar Coast", "59,700", "<h1>The Western Ghats Region</h1><br>The mountains along the west coast of peninsular India are the Western Ghats, which constitute one of the unique biological regions of the world. The Western Ghats extend from the southern tip of the peninsula (8°N) northwards about 1600 km to the mouth of the river Tapti (21°N).\n" +
                "\n" +
                "<br><br>The mountains rise to average altitudes between 900 and 1500 m above sea level, intercepting monsoon winds from the southwest and creating a rain shadow in the region to their East.\n" +
                "\n" +
                "<br><br>The varied climate and diverse topography create a wide array of habitats that support unique sets of plant and animal species. Apart from biological diversity, the region boasts of high levels of cultural diversity, as many indigenous people inhabit its forests.\n" +
                "\n" +
                "<br><br>The Western Ghats are amongst the 25 biodiversity hot-spots recognized globally. These hills are known for their high levels of endemism expressed at both higher and lower taxonomic levels. Most of the Western Ghat endemic plants are associated with evergreen forests.\n" +
                "\n" +
                "<br><br>The region also shares several plant species with Sri Lanka. The higher altitude forests were, if at all, sparsely populated with tribal people. Rice cultivation in the fertile valley proceeded gardens of early commercial crops like areca nut and pepper. The original vegetation of the ill-drained valley bottoms with sluggish streams in elevations below 100m would be often a special formation, the Myristica swamp.\n" +
                "\n" +
                "<br><br>Expansion of traditional agriculture and the spread of particularly rubber, tea, coffee and forest tree plantations would have wiped out large pockets of primary forests in valleys. The Western Ghats are well known for harboring 14 endemic species of caecilians (i.e., legless amphibians) out of 15 recorded from the region so far.\n" +
                "\n"));
        regions.add(new Region("", "Western Ghat Mountains", "99,300", "<h1>The Western Ghats Region</h1><br>The mountains along the west coast of peninsular India are the Western Ghats, which constitute one of the unique biological regions of the world. The Western Ghats extend from the southern tip of the peninsula (8°N) northwards about 1600 km to the mouth of the river Tapti (21°N).\n" +
        "\n" +
                "<br><br>The mountains rise to average altitudes between 900 and 1500 m above sea level, intercepting monsoon winds from the southwest and creating a rain shadow in the region to their East.\n" +
                "\n" +
                "<br><br>The varied climate and diverse topography create a wide array of habitats that support unique sets of plant and animal species. Apart from biological diversity, the region boasts of high levels of cultural diversity, as many indigenous people inhabit its forests.\n" +
                "\n" +
                "<br><br>The Western Ghats are amongst the 25 biodiversity hot-spots recognized globally. These hills are known for their high levels of endemism expressed at both higher and lower taxonomic levels. Most of the Western Ghat endemic plants are associated with evergreen forests.\n" +
                "\n" +
                "<br><br>The region also shares several plant species with Sri Lanka. The higher altitude forests were, if at all, sparsely populated with tribal people. Rice cultivation in the fertile valley proceeded gardens of early commercial crops like areca nut and pepper. The original vegetation of the ill-drained valley bottoms with sluggish streams in elevations below 100m would be often a special formation, the Myristica swamp.\n" +
                "\n" +
                "<br><br>Expansion of traditional agriculture and the spread of particularly rubber, tea, coffee and forest tree plantations would have wiped out large pockets of primary forests in valleys. The Western Ghats are well known for harboring 14 endemic species of caecilians (i.e., legless amphibians) out of 15 recorded from the region so far.\n" +
                "\n"));

        regions.add(new Region("Deccan Peninsula", "Deccan Plateau South", "378,000", "<h1>The Deccan Peninsula Region</h1><br>Beyond the Ghats is Deccan Plateau, a semi-arid region lying in the rain shadow of the Western Ghats. This is the largest unit of the Peninsular Plateau of India. The highlands of the plateau are covered with different types of forests, which provide a large variety of forest products.the Deccan plateau includes the region lying south of the Satpura range.it extends up to the southern tip of peninsular India.Anai mudi is the highest peak of this region.The Deccan plateau is surrounded by the western and the eastern ghats.These ghats meet each other at the Nilgiri hills. The western ghats includes the Sahyadri, Nilgiris, Anamalai, and cardamom hills.many rivers such as Mahanadi, Godavari, krishna, and kaveri originates from western ghats and flow toward the east.The eastern ghats are broken into small hill rangesby river coming from the western ghats.Most of these rivers fall into the bay of Bengal.The Godavari is the longest river in the Deccan plateau .the Narmada and the Tapi flow westwards and fall into the Arabian sea.\n" +
                "\n"));
        regions.add(new Region("", "Central Plateau", "341,000", "<h1>The Deccan Peninsula Region</h1><br>Beyond the Ghats is Deccan Plateau, a semi-arid region lying in the rain shadow of the Western Ghats. This is the largest unit of the Peninsular Plateau of India. The highlands of the plateau are covered with different types of forests, which provide a large variety of forest products.the Deccan plateau includes the region lying south of the Satpura range.it extends up to the southern tip of peninsular India.Anai mudi is the highest peak of this region.The Deccan plateau is surrounded by the western and the eastern ghats.These ghats meet each other at the Nilgiri hills. The western ghats includes the Sahyadri, Nilgiris, Anamalai, and cardamom hills.many rivers such as Mahanadi, Godavari, krishna, and kaveri originates from western ghats and flow toward the east.The eastern ghats are broken into small hill rangesby river coming from the western ghats.Most of these rivers fall into the bay of Bengal.The Godavari is the longest river in the Deccan plateau .the Narmada and the Tapi flow westwards and fall into the Arabian sea.\n" +
        "\n"));
        regions.add(new Region("", "Eastern Plateau", "198,000", "<h1>The Deccan Peninsula Region</h1><br>Beyond the Ghats is Deccan Plateau, a semi-arid region lying in the rain shadow of the Western Ghats. This is the largest unit of the Peninsular Plateau of India. The highlands of the plateau are covered with different types of forests, which provide a large variety of forest products.the Deccan plateau includes the region lying south of the Satpura range.it extends up to the southern tip of peninsular India.Anai mudi is the highest peak of this region.The Deccan plateau is surrounded by the western and the eastern ghats.These ghats meet each other at the Nilgiri hills. The western ghats includes the Sahyadri, Nilgiris, Anamalai, and cardamom hills.many rivers such as Mahanadi, Godavari, krishna, and kaveri originates from western ghats and flow toward the east.The eastern ghats are broken into small hill rangesby river coming from the western ghats.Most of these rivers fall into the bay of Bengal.The Godavari is the longest river in the Deccan plateau .the Narmada and the Tapi flow westwards and fall into the Arabian sea.\n" +
        "\n"));
        regions.add(new Region("", "Chhota Nagpur", "217,000", "<h1>The Deccan Peninsula Region</h1><br>Beyond the Ghats is Deccan Plateau, a semi-arid region lying in the rain shadow of the Western Ghats. This is the largest unit of the Peninsular Plateau of India. The highlands of the plateau are covered with different types of forests, which provide a large variety of forest products.the Deccan plateau includes the region lying south of the Satpura range.it extends up to the southern tip of peninsular India.Anai mudi is the highest peak of this region.The Deccan plateau is surrounded by the western and the eastern ghats.These ghats meet each other at the Nilgiri hills. The western ghats includes the Sahyadri, Nilgiris, Anamalai, and cardamom hills.many rivers such as Mahanadi, Godavari, krishna, and kaveri originates from western ghats and flow toward the east.The eastern ghats are broken into small hill rangesby river coming from the western ghats.Most of these rivers fall into the bay of Bengal.The Godavari is the longest river in the Deccan plateau .the Narmada and the Tapi flow westwards and fall into the Arabian sea.\n" +
        "\n"));
        regions.add(new Region("", "Central Highlands", "287,000", "<h1>The Deccan Peninsula Region</h1><br>Beyond the Ghats is Deccan Plateau, a semi-arid region lying in the rain shadow of the Western Ghats. This is the largest unit of the Peninsular Plateau of India. The highlands of the plateau are covered with different types of forests, which provide a large variety of forest products.the Deccan plateau includes the region lying south of the Satpura range.it extends up to the southern tip of peninsular India.Anai mudi is the highest peak of this region.The Deccan plateau is surrounded by the western and the eastern ghats.These ghats meet each other at the Nilgiri hills. The western ghats includes the Sahyadri, Nilgiris, Anamalai, and cardamom hills.many rivers such as Mahanadi, Godavari, krishna, and kaveri originates from western ghats and flow toward the east.The eastern ghats are broken into small hill rangesby river coming from the western ghats.Most of these rivers fall into the bay of Bengal.The Godavari is the longest river in the Deccan plateau .the Narmada and the Tapi flow westwards and fall into the Arabian sea.\n" +
        "\n"));

        regions.add(new Region("Gangetic Plain", "Upper Gangetic Plain", "206,400", "<h1>The Gangetic Plains</h1><br>In the North is the Gangetic plain extending up to the Himalayan foothills. This is the largest unit of the Great Plain of India. Ganga is the main river after whose name this plain is named. The aggradational Great Plains cover about 72.4mha area with the Ganga and the Brahmaputra forming the main drainage axes in the major portion.<br><br>The thickness in the alluvial sediments varies considerably with its maximum in the Ganga plains. The physiogeographic scenery varies greatly from arid and semi-arid landscapes of the Rajasthan Plains to the humid and per-humid landscapes of the Delta and Assam valley in the east.<br><br>Topographic uniformity, except in the arid Western Rajasthan is a common feature throughout these plains. The plain supports some of the highest population densities depending upon purely agro-based economy in some of these areas. The trees belonging to these forests are teak, sal, shisham, mahua, khair etc."));
        regions.add(new Region("", "Lower Gangetic Plain", "153,000", "<h1>The Gangetic Plains</h1><br>In the North is the Gangetic plain extending up to the Himalayan foothills. This is the largest unit of the Great Plain of India. Ganga is the main river after whose name this plain is named. The aggradational Great Plains cover about 72.4mha area with the Ganga and the Brahmaputra forming the main drainage axes in the major portion.<br><br>The thickness in the alluvial sediments varies considerably with its maximum in the Ganga plains. The physiogeographic scenery varies greatly from arid and semi-arid landscapes of the Rajasthan Plains to the humid and per-humid landscapes of the Delta and Assam valley in the east.<br><br>Topographic uniformity, except in the arid Western Rajasthan is a common feature throughout these plains. The plain supports some of the highest population densities depending upon purely agro-based economy in some of these areas. The trees belonging to these forests are teak, sal, shisham, mahua, khair etc."));

        regions.add(new Region("North East India", "Brahmaputra Valley", "65,200", "<h1>North-East Region</h1><br>North-east India is one of the richest flora regions in the country. It has several species of orchids, bamboos, ferns and other plants. Here the wild relatives of cultivated plants such as banana, mango, citrus and pepper can be grown."));
        regions.add(new Region("", "North Eastern Hills", "106,200", "<h1>North-East Region</h1><br>North-east India is one of the richest flora regions in the country. It has several species of orchids, bamboos, ferns and other plants. Here the wild relatives of cultivated plants such as banana, mango, citrus and pepper can be grown."));

        regions.add(new Region("Islands", "Andaman Islands", "6397", "<h1>Islands Region</h1><br>The two groups of islands, i.e., the Arabian Sea islands and Bay Islands differ significantly in origin and physical characteristics. The Arabian Sea Islands (Laccadive, Minicoy, etc.) are the foundered remnants of the old land mass and subsequent coral formations. On the other hand, the Bay Islands lay only about 220 km.<br><br>Away from the nearest point on the main land mass and extend about 590 km. With a maximum width of 58 km the island forests of Lakshadweep in the Arabian Sea have some of the best-preserved evergreen forests of India. Some of the islands are fringed with coral reefs. Many of them are covered with thick forests and some are highly dissected."));
        regions.add(new Region("", "Nicobar Islands", "1930", "<h1>Islands Region</h1><br>The two groups of islands, i.e., the Arabian Sea islands and Bay Islands differ significantly in origin and physical characteristics. The Arabian Sea Islands (Laccadive, Minicoy, etc.) are the foundered remnants of the old land mass and subsequent coral formations. On the other hand, the Bay Islands lay only about 220 km.<br><br>Away from the nearest point on the main land mass and extend about 590 km. With a maximum width of 58 km the island forests of Lakshadweep in the Arabian Sea have some of the best-preserved evergreen forests of India. Some of the islands are fringed with coral reefs. Many of them are covered with thick forests and some are highly dissected."));
        regions.add(new Region("", "Laksadweep Islands", "180", "<h1>Islands Region</h1><br>The two groups of islands, i.e., the Arabian Sea islands and Bay Islands differ significantly in origin and physical characteristics. The Arabian Sea Islands (Laccadive, Minicoy, etc.) are the foundered remnants of the old land mass and subsequent coral formations. On the other hand, the Bay Islands lay only about 220 km.<br><br>Away from the nearest point on the main land mass and extend about 590 km. With a maximum width of 58 km the island forests of Lakshadweep in the Arabian Sea have some of the best-preserved evergreen forests of India. Some of the islands are fringed with coral reefs. Many of them are covered with thick forests and some are highly dissected."));

        regions.add(new Region("Coasts", "West Coast", "6500", "<h1>The Coastal Region</h1><br>India has a coastline extending over 7,516. 4 km. The Indian coasts vary in their characteristics and structures. The west coast is narrow except around the Gulf of Cambay and the Gulf of Kutch. In the extreme south, however, it is somewhat wider along the south Sahyadri.<br><br>The backwaters are the characteristic features of this coast. The east coast plains, in contrast are broader due to depositional activities of the east-flowing rivers owing to the change in their base levels.<br><br>Extensive deltas of the, Godavari, Krishna and Kaveri are the characteristic features of this coast. Mangrove vegetation is characteristic of estuarine tracts along the coast for instance, at Ratnagiri in Maharashtra.<br><br>Larger parts of the coastal plains are covered by fertile soils on which different crops are grown. Rice is the main crop of these areas. Coconut trees grow all along the coast.<br><br>Coconut and rubber are the main vegetation of coastal area. The main states of coastal areas are- Gujarat, Maharashtra, Goa, Karnataka, Kerala, west Bengal, Odisha, Andra pradesh, Tamil Nadu and Puducherry."));
        regions.add(new Region("", "East Coast", "6500", "<h1>The Coastal Region</h1><br>India has a coastline extending over 7,516. 4 km. The Indian coasts vary in their characteristics and structures. The west coast is narrow except around the Gulf of Cambay and the Gulf of Kutch. In the extreme south, however, it is somewhat wider along the south Sahyadri.<br><br>The backwaters are the characteristic features of this coast. The east coast plains, in contrast are broader due to depositional activities of the east-flowing rivers owing to the change in their base levels.<br><br>Extensive deltas of the, Godavari, Krishna and Kaveri are the characteristic features of this coast. Mangrove vegetation is characteristic of estuarine tracts along the coast for instance, at Ratnagiri in Maharashtra.<br><br>Larger parts of the coastal plains are covered by fertile soils on which different crops are grown. Rice is the main crop of these areas. Coconut trees grow all along the coast.<br><br>Coconut and rubber are the main vegetation of coastal area. The main states of coastal areas are- Gujarat, Maharashtra, Goa, Karnataka, Kerala, west Bengal, Odisha, Andra pradesh, Tamil Nadu and Puducherry."));



        RegionAdapter regionAdapter = new RegionAdapter(this, regions);

        RecyclerView recyclerView = findViewById(R.id.recycler);
        recyclerView.setAdapter(regionAdapter);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));

        DividerItemDecoration dividerItemDecoration = new DividerItemDecoration(this, DividerItemDecoration.VERTICAL);
        recyclerView.addItemDecoration(dividerItemDecoration);
    }
}
